### ISSUE TITLE
Install on MacOSX

### ISSUE THREAD

**Issue by jgrethe** [MetaCell/sds-viewer#101]
Had node and yarn already for other projects. Went through the clone and build (only got warnings).  Running the app it reports:

Compiled with warnings.

src/components/FileUploader/UploadView/UploadProgress.js
  Line 25:6:  React Hook useEffect has missing dependencies: 'file' and 'onUpload'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

src/components/FileUploader/UrlUploader.js
  Line 59:19:  Array.prototype.map() expects a return value from arrow function                                                                                                                                                                  array-callback-return
  Line 82:3:   React Hook useEffect contains a call to 'setLoader'. Without a list of dependencies, this can lead to an infinite chain of updates. To fix this, pass [loader, fileDownloaded, files] as a second argument to the useEffect Hook  react-hooks/exhaustive-deps

src/components/GraphViewer/GraphViewer.js
  Line 69:10:  'resize' is assigned a value but never used  no-unused-vars

src/components/NodeDetailView/Details/DatasetDetails.js
  Line 11:8:   'CustomChips' is defined but never used                           no-unused-vars
  Line 42:82:  Array.prototype.map() expects a return value from arrow function  array-callback-return
  Line 53:63:  Array.prototype.map() expects a return value from arrow function  array-callback-return

src/components/NodeDetailView/Details/Views/Breadcrumbs.js
  Line 3:8:    'CLOSE' is defined but never used                 no-unused-vars
  Line 4:10:   'useSelector' is defined but never used           no-unused-vars
  Line 6:10:   'WidgetStatus' is defined but never used          no-unused-vars
  Line 11:18:  'close' is assigned a value but never used        no-unused-vars
  Line 18:9:   'closeViewer' is assigned a value but never used  no-unused-vars

src/components/NodeDetailView/Headers/CollectionHeader.js
  Line 3:8:  'Breadcrumbs' is defined but never used  no-unused-vars

src/components/NodeDetailView/Headers/DatasetHeader.js
  Line 3:8:  'Breadcrumbs' is defined but never used  no-unused-vars

src/components/NodeDetailView/Headers/FileHeader.js
  Line 3:8:  'Breadcrumbs' is defined but never used  no-unused-vars

src/components/NodeDetailView/Headers/PersonHeader.js
  Line 3:8:  'Breadcrumbs' is defined but never used  no-unused-vars

src/components/NodeDetailView/Headers/ProtocolHeader.js
  Line 3:8:  'Breadcrumbs' is defined but never used  no-unused-vars

src/components/NodeDetailView/factory.js
  Line 1:10:  'NODES' is defined but never used  no-unused-vars

src/components/Sidebar/Footer.js
  Line 1:8:   'Help' is defined but never used                no-unused-vars
  Line 4:8:   'ArrowRight' is defined but never used          no-unused-vars
  Line 5:15:  'IconButton' is defined but never used          no-unused-vars
  Line 5:27:  'Typography' is defined but never used          no-unused-vars
  Line 8:11:  'expand' is assigned a value but never used     no-unused-vars
  Line 8:19:  'setExpand' is assigned a value but never used  no-unused-vars

src/components/Sidebar/TreeView/InstancesTreeView.js
  Line 110:6:  React Hook useEffect has missing dependencies: 'datasets' and 'searchTree'. Either include them or remove the dependency array                                                                                            react-hooks/exhaustive-deps
  Line 113:3:  React Hook useEffect contains a call to 'setItems'. Without a list of dependencies, this can lead to an infinite chain of updates. To fix this, pass [items.length, datasets] as a second argument to the useEffect Hook  react-hooks/exhaustive-deps

src/redux/middleware.js
  Line 1:13:  'GeppettoActions' is defined but never used  no-unused-vars

src/utils/Splinter.js
  Line 564:21:  'index' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by jgrethe** [comment]
And then all I end up with (after waiting to see if anything shows up), after dismissing the message, is a white window

![image](https://user-images.githubusercontent.com/1634917/136621542-eaa38326-f2ec-4525-9206-14c9c5ed7328.png)

**Comment by jrmartin** [comment]
Thanks for the detailed description @jgrethe, looking into it.

**Comment by jrmartin** [comment]
Hey @ddelpiano , can you test in Mac if you get this error? It's happening after 'yarn start', in Linux is working fine.

**Comment by jgrethe** [comment]
Just an FYI - if there is a version issue:
