### ISSUE TITLE
Load Dataset by passing ID

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/sds-viewer#111]

**Comment by ddelpiano** [comment]
@jrmartin what should I do for the version here? 
I can build a logic up for the id and it would be pretty straight forward working on some assumptions (cassava url and file name keeping the same structure as now) but for the version we never continued.
Moving this to the ice box for now until the requirements are filled. Thx

**Comment by jrmartin** [comment]
@ddelpiano We can move this one out of the ice box. I confirm today we can discard the version, and just use the dataset id

Something like this would work:
http://localhost:3000/sds-viewer?datasetID=3A1873396f-8d82-4d6c-93f7-52117470e4a1

**Comment by jrmartin** [comment]
Add json configuration to specify which dataset folder to use.
