### ISSUE TITLE
See Hierarchical View

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/sds-viewer#13]
User Story: 
I want to Visualize datasets in hierarchical view component
so I can Navigate datasets as if I was using the system's file explorer

This issue is split into three cards:
1) Creating the component on the left side bar, the hierarchical view.
https://github.com/MetaCell/sds-viewer/issues/44

2) Creating the UI for the dataset loader.
https://github.com/MetaCell/sds-viewer/issues/43

3) Extracting the dataset  items to display in this component
https://github.com/MetaCell/sds-viewer/issues/9

Once all 3 steps are done , the component will need to be populated with the data from step 3.

**Comment by jrmartin** [comment]
Closing this card, task handled by issue #66
