### ISSUE TITLE
SDS Viewer Next Steps - Estimate Plan

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/sds-viewer#132]
- Missing Descriptions for Datasets Metadata. Maybe make the Labels bold.
- For Datasets, not clear that the label property is the title.
- Derivatives not showing next to primary for sparc:samples and sparc:subjects. We need to consume both 'collections' under TEMP:hasFolderAboutIt
- Show files on same level as sparc:sample. E.G. If sparc:subject has sparc:sample and files, then latter two are siblings on same level.

**Comment by ddelpiano** [comment]
missing description (not in the original requirement, new feature)

example from dataset:1b137c7e-2f07-4a78-8079-828b37743306
```
    dc:description "This data set describes staining of submandibular ganglion with α-bungarotoxin (BTX) and nanosensor developed by the Clark lab. BTX staining is used as gold standard to validate localization of nanosensor. This data set contains fluorescence multichannel images of stained submandibular ganglion taken from a Zeiss confocal microscope. The images can be viewed by ZEN software https://www.zeiss.com/microscopy/us/products/microscope-software/zen-lite.html" ;
```
