### ISSUE TITLE
SDS Viewer Tests

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/sds-viewer#151]
Deployment
https://metacell.github.io/sds-viewer/

ReadMe 
https://github.com/MetaCell/sds-viewer#readme

**Comment by SimaoBolota-MetaCell** [comment]
Tests progress can be found here https://metacell.atlassian.net/projects/SDSV?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCycles?projectId=10021
