### ISSUE TITLE
Moving inbetween dataset tabs makes the file tree disappear

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [MetaCell/sds-viewer#172]
By moving to another tab and clicking on its content, the viewer of the other tab disappears when going back to it, eventhough the tab exists 

https://user-images.githubusercontent.com/99416933/230153642-923204e6-da91-4c31-a59e-4034ecf7551c.mov

**Comment by jrmartin** [comment]
Handled by branch feature/177
