### ISSUE TITLE
May 19 Feedback

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/sds-viewer#175]
- Submit wireframe request to SPARC portal, to be able to launch SDS Viewer from the portal.
- Usability testing group : Brainstorm usable tasks
-  Graph loses place when selecting a node. 
- Filter groups 
- Expand/collapse subjects all the way to file level. Same for other nodes?
- Different icons for different groups

**Comment by tgbugs** [comment]
1. yes open the full subtree when clicking on a folder
2. folder should show the total nested number of files not just the immediate children
