### ISSUE TITLE
Load RDF Turtle Files

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/sds-viewer#18]
as a Any User
I want to Load RDF turtle files from local system
so I can Visualize the structure and hierarchy of the SPARC study dataset and associated metadata

**Comment by jrmartin** [comment]
RDF turtle files can be found here https://cassava.ucsd.edu/sparc/preview/archive/exports/2021-04-12T17%3A28%3A22%2C384227-07%3A00/datasets/. @ddelpiano
