### ISSUE TITLE
Upload UI for local and external datasets

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/sds-viewer#43]
The design upload UI for local and external datasets:
![image.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/ecec5a28-07f5-45a1-92be-d56e11e5a5bf)

User wants to upload files from local system and using an external URL. Files are expected to be no bigger than 5 mb.

**Comment by jrmartin** [comment]
Design upload UI for local and external datasets
![image.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/ecec5a28-07f5-45a1-92be-d56e11e5a5bf)

**Comment by vidhya-metacell** [comment]
@jrmartin @zsinnema what should be the file extensions and max file size that would be acceptable for upload on the drop zone area.

**Comment by jrmartin** [comment]
> @jrmartin @zsinnema what should be the file extensions and max file size that would be acceptable for upload on the drop zone area.

@vidhya-metacell The file extensions should be .json and .ttl . The max file size should be 5mb.
