### ISSUE TITLE
Process Dataset to use in Graph

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/sds-viewer#9]
As Any User : I want to Process turtle file dataset into json or graph format, so I can see the dataset as a graph.

List of different datasets we can use: https://cassava.ucsd.edu/sparc/preview/archive/exports/2021-04-12T17%3A28%3A22%2C384227-07%3A00/datasets/

A complex example is this dataset:  https://cassava.ucsd.edu/sparc/preview/archive/exports/2021-04-12T17%3A28%3A22%2C384227-07%3A00/datasets/N:dataset:80a485bf-0d9d-425d-9f51-94b59f842ede.ttl

Along with the RDF turtle file, we need to process the metadata file to create the graph , example for RDF turtle link above : https://cassava.ucsd.edu/sparc/preview/archive/exports/2021-04-12T17%3A28%3A22%2C384227-07%3A00/path-metadata/80a485bf-0d9d-425d-9f51-94b59f842ede/

A simple dataset example is this the with ID : dataset:29df9b97-a20b-469c-bf48-9389f1e31a11

**Comment by jrmartin** [comment]
@ddelpiano This will be the final form of the graph once all the dataset is processed and we start working on the groups. https://app.zenhub.com/workspaces/sds-viewer-60adefcebe2dfe0017ff66b1/issues/metacell/sds-viewer/56#issuecomment-884551404
