### ISSUE TITLE
Review Pull Requests

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/sds-viewer#96]
These are the PR's for the SDS Viewer that are ready for review. I put them in order of what it would be easier to review first and merged.

This is the first PR that should be review, contains the work for issue #66.
https://github.com/MetaCell/sds-viewer/pull/72

This PR is to merge a fix into branch feature/15_2. Dario is assigned as reviewer but you can review it instead if you have a chance.
https://github.com/MetaCell/sds-viewer/pull/93

This can be merged after the previous two PR's (72 and 93) are merged, it would be easier that way.
https://github.com/MetaCell/sds-viewer/pull/87

Graph Viewer layout fixes. This is one is easier to merge after PR #87 gets merged.
https://github.com/MetaCell/sds-viewer/pull/94

**Comment by zsinnema** [comment]
@jrmartin please can you have a look at the merge conflicts in #87 ? thanks!
